spring:
  datasource:
    url: jdbc:mysql://localhost:3306/how2java?useUnicode=true&characterEncoding=UTF8
    username: root
    password: 765970426
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  thymeleaf:
    cache: false
    encoding: utf-8
    content-type: text/html
    mode: HTML5
  application:
    name: myDrugList
server:
  port: 8900
logging:
    level:
       com.sun.drug.repository: DEBUG
